print("Deseja visualizar as tabuadas de 1 a 10?")
selection = input("1. Sim \n2. Não")
if selection == "1":

    num1 = 1
    print("="*20)
    print("{} X {} = {}".format(num1,1,num1*1))
    print("{} X {} = {}".format(num1,2,num1*2))
    print("{} X {} = {}".format(num1,3,num1*3))
    print("{} X {} = {}".format(num1,4,num1*4))
    print("{} X {} = {}".format(num1,5,num1*5))
    print("{} X {} = {}".format(num1,6,num1*6))
    print("{} X {} = {}".format(num1,7,num1*7))
    print("{} X {} = {}".format(num1,8,num1*8))
    print("{} X {} = {}".format(num1,9,num1*9))
    print("{} X {} = {}".format(num1,10,num1*10))
    print("="*20)

    num2 = 2
    print("="*20)
    print("{} X {} = {}".format(num2,1,num2*1))
    print("{} X {} = {}".format(num2,2,num2*2))
    print("{} X {} = {}".format(num2,3,num2*3))
    print("{} X {} = {}".format(num2,4,num2*4))
    print("{} X {} = {}".format(num2,5,num2*5))
    print("{} X {} = {}".format(num2,6,num2*6))
    print("{} X {} = {}".format(num2,7,num2*7))
    print("{} X {} = {}".format(num2,8,num2*8))
    print("{} X {} = {}".format(num2,9,num2*9))
    print("{} X {} = {}".format(num2,10,num2*10))
    print("="*20)

    num3 = 3
    print("="*20)
    print("{} X {} = {}".format(num3,1,num3*1))
    print("{} X {} = {}".format(num3,2,num3*2))
    print("{} X {} = {}".format(num3,3,num3*3))
    print("{} X {} = {}".format(num3,4,num3*4))
    print("{} X {} = {}".format(num3,5,num3*5))
    print("{} X {} = {}".format(num3,6,num3*6))
    print("{} X {} = {}".format(num3,7,num3*7))
    print("{} X {} = {}".format(num3,8,num3*8))
    print("{} X {} = {}".format(num3,9,num3*9))
    print("{} X {} = {}".format(num3,10,num3*10))
    print("="*20)

    num4 = 4
    print("="*20)
    print("{} X {} = {}".format(num4,1,num4*1))
    print("{} X {} = {}".format(num4,2,num4*2))
    print("{} X {} = {}".format(num4,3,num4*3))
    print("{} X {} = {}".format(num4,4,num4*4))
    print("{} X {} = {}".format(num4,5,num4*5))
    print("{} X {} = {}".format(num4,6,num4*6))
    print("{} X {} = {}".format(num4,7,num4*7))
    print("{} X {} = {}".format(num4,8,num4*8))
    print("{} X {} = {}".format(num4,9,num4*9))
    print("{} X {} = {}".format(num4,10,num4*10))
    print("="*20)

    num5 = 5
    print("="*20)
    print("{} X {} = {}".format(num5,1,num5*1))
    print("{} X {} = {}".format(num5,2,num5*2))
    print("{} X {} = {}".format(num5,3,num5*3))
    print("{} X {} = {}".format(num5,4,num5*4))
    print("{} X {} = {}".format(num5,5,num5*5))
    print("{} X {} = {}".format(num5,6,num5*6))
    print("{} X {} = {}".format(num5,7,num5*7))
    print("{} X {} = {}".format(num5,8,num5*8))
    print("{} X {} = {}".format(num5,9,num5*9))
    print("{} X {} = {}".format(num5,10,num5*10))
    print("="*20)

    num6 = 6
    print("="*20)
    print("{} X {} = {}".format(num6,1,num6*1))
    print("{} X {} = {}".format(num6,2,num6*2))
    print("{} X {} = {}".format(num6,3,num6*3))
    print("{} X {} = {}".format(num6,4,num6*4))
    print("{} X {} = {}".format(num6,5,num6*5))
    print("{} X {} = {}".format(num6,6,num6*6))
    print("{} X {} = {}".format(num6,7,num6*7))
    print("{} X {} = {}".format(num6,8,num6*8))
    print("{} X {} = {}".format(num6,9,num6*9))
    print("{} X {} = {}".format(num6,10,num6*10))
    print("="*20)

    num7 = 7
    print("="*20)
    print("{} X {} = {}".format(num7,1,num7*1))
    print("{} X {} = {}".format(num7,2,num7*2))
    print("{} X {} = {}".format(num7,3,num7*3))
    print("{} X {} = {}".format(num7,4,num7*4))
    print("{} X {} = {}".format(num7,5,num7*5))
    print("{} X {} = {}".format(num7,6,num7*6))
    print("{} X {} = {}".format(num7,7,num7*7))
    print("{} X {} = {}".format(num7,8,num7*8))
    print("{} X {} = {}".format(num7,9,num7*9))
    print("{} X {} = {}".format(num7,10,num7*10))
    print("="*20)

    num8 = 8
    print("="*20)
    print("{} X {} = {}".format(num8,1,num8*1))
    print("{} X {} = {}".format(num8,2,num8*2))
    print("{} X {} = {}".format(num8,3,num8*3))
    print("{} X {} = {}".format(num8,4,num8*4))
    print("{} X {} = {}".format(num8,5,num8*5))
    print("{} X {} = {}".format(num8,6,num8*6))
    print("{} X {} = {}".format(num8,7,num8*7))
    print("{} X {} = {}".format(num8,8,num8*8))
    print("{} X {} = {}".format(num8,9,num8*9))
    print("{} X {} = {}".format(num8,10,num8*10))
    print("="*20)

    num9 = 9
    print("="*20)
    print("{} X {} = {}".format(num9,1,num9*1))
    print("{} X {} = {}".format(num9,2,num9*2))
    print("{} X {} = {}".format(num9,3,num9*3))
    print("{} X {} = {}".format(num9,4,num9*4))
    print("{} X {} = {}".format(num9,5,num9*5))
    print("{} X {} = {}".format(num9,6,num9*6))
    print("{} X {} = {}".format(num9,7,num9*7))
    print("{} X {} = {}".format(num9,8,num9*8))
    print("{} X {} = {}".format(num9,9,num9*9))
    print("{} X {} = {}".format(num9,10,num9*10))
    print("="*20)

    num10 = 10
    print("="*20)
    print("{} X {} = {}".format(num10,1,num10*1))
    print("{} X {} = {}".format(num10,2,num10*2))
    print("{} X {} = {}".format(num10,3,num10*3))
    print("{} X {} = {}".format(num10,4,num10*4))
    print("{} X {} = {}".format(num10,5,num10*5))
    print("{} X {} = {}".format(num10,6,num10*6))
    print("{} X {} = {}".format(num10,7,num10*7))
    print("{} X {} = {}".format(num10,8,num10*8))
    print("{} X {} = {}".format(num10,9,num10*9))
    print("{} X {} = {}".format(num10,10,num10*10))
    print("="*20)

else:
    print("Tudo bem, você fez sua escolha!")



